import Core.LogUtils as LogUtils
import Core.KeyDirUtils as KeyDirUtils
import Core.ConfigParser as ConfigParser
import Core.EnvironmentChecker as EnvironmentChecker
import subprocess, os, copy, json

class ImageInfoUtils:

    def __init__(self, logger = None) -> None:
        self.TAG = "ImageInfoUtils"
        if not logger:
            self.myLogger = LogUtils.LogUtils()
            self.myLogger.log("W", "Logger not given, created an instance just now.", self.TAG)
        else:
            self.myLogger = logger
        self.myLogger.log("I", "Instance of ImageInfoUtils successfully created.", self.TAG)

    def log_if_debug(self, log_level ="T",
                     log_str ="Default log generated by logIfDebug"):
        self.myLogger.log(log_level, log_str, self.TAG)
    
    def check_image_exists(self, image_info_list : list[str], image_dir = None):
        if image_dir is None:
            image_dir = os.path.join(os.getcwd(), "Images")
        existing_images = []
        for filename in os.listdir(image_dir):
            if filename.endswith(".img"):
                existing_images.append(filename[:-4:])
            else:
                existing_images.append(filename)
        existing_images.sort()
        image_info_list.sort()
        set_existing = set(existing_images)
        set_image_info_list = set(image_info_list)
        if set_existing == set_image_info_list:
            self.myLogger.log("D", str((True, "EQUAL", set_existing)), self.TAG)
            return True, "EQUAL", set_existing
        else:
            self.myLogger.log("D", str((False, set_existing.difference(set_image_info_list), set_existing, set_image_info_list)), self.TAG)
            if len(existing_images) > len(image_info_list):
                self.myLogger.log("W", "MORE", self.TAG)
                return False, "MORE", set_existing.difference(set_image_info_list), set_existing, set_image_info_list
            if len(existing_images) < len(image_info_list):
                self.myLogger.log("W", "LESS", self.TAG)
                return False, "LESS", set_existing.difference(set_image_info_list), set_existing, set_image_info_list
            else:
                self.myLogger.log("W", "DIFF", self.TAG)
                return False, "DIFF", set_existing.difference(set_image_info_list), set_existing, set_image_info_list
            

    def read_image_info(self, image_name : str) -> str:
        """
        Read footer of a SINGLE IMAGE. retval: string
        Will raise RuntimeException when operation cannot be finished due to wrong OS or ENOENT.

        :param image_name: image file's name, method will autocorrect it to ".img".
        :return: image_info string
        """
        if not image_name.endswith(".img"):
            image_name += ".img"

        self.myLogger.log("D", "Reading image info: " + image_name)

        command_header = EnvironmentChecker.EnvironmentChecker.detect_python_command()

        if command_header is None:
            self.myLogger.log("W", "Unable to find proper Python")
            raise RuntimeError("Unable to find proper Python")

        command_list = [command_header,
                       os.path.join(os.getcwd(), "Core", "avbtool.py"),
                       "info_image",
                       "--image",
                       os.path.join(os.getcwd(), "Images", image_name)]

        # Add capture_output and text args to ensure object "result" contains output content    
        result = subprocess.run(command_list, capture_output=True, text=True)
        if result.returncode == 0:
            self.log_if_debug("T", "Successfully executed \"avbtool info_image\" command.")
            return str(result.stdout)
        else:
            self.log_if_debug("W", "avbtool.py returned non-zero exit code. Check next line of log for detailed information.")
            # Process standard error, we don't need usage tips.
            error_content = str(result.stderr)
            if "does not look like" in error_content:
                self.myLogger.log("W", "You are reading a image without avb footer.", "ImageInfoUtils")
                self.myLogger.log("D", "Maybe AVBPowerTool encountered unhandled exception in signing stage.")
                self.myLogger.log("D", "Or much simpler, the problem is in image itself.")
                raise RuntimeError("Non-vbmeta image.")
            error_content = error_content[error_content.find("error:"):].strip("\n")
            self.myLogger.log("W", "Error info: " + error_content, "ImageInfoUtils")
            # Provide special tip for ERRNO 2.
            if "Errno 2" in error_content:
                self.myLogger.log("W", "Image file not found. Check your image dir.")
                if os.name == "nt":            
                    self.myLogger.log("W", "You are running this program on Windows, Linux environment is recommended.")
            raise RuntimeError("avbtool.py encountered an issue, fix it and restart the program.")

    def __image_info_parser(self, image_info_string : str, is_vbmeta_image = False) -> dict:
        """
        Convert string result to a dictionary that contains footer info.
        Will call private method __generateConfigDict() or __generateConfigDictVB() to finally generate result dictionary.
        is_vbmeta_image is an optional arg that allows you to parse image as vbmeta format.
        """
        if is_vbmeta_image:
            self.myLogger.log("I", "Processing a VBMeta image.", "imageInfoParser")
        image_info_list = image_info_string.split("\n")
        self.log_if_debug("T", "Step 1, split image info string into list by symbol \\n:")
        for info_line in image_info_list:
            self.log_if_debug("T", info_line)
        self.log_if_debug("T", "Step2, delete useless spaces and parse them into key-value pairs.")
        prop_count = 0
        '''
        Less information are required when creating a vbmeta image.
        Thus allowing we process them in this method instead of extracting this logic.
        '''
        if is_vbmeta_image:
            # The sequence of list "Chain" and list "Chain partition key" are the same.
            # You can easily use one "for" loop to convert usable "include chain partition" command line
            result_dic = {"Chain" : [], # Store chain partition name and rollback index location
                         "Chain partition key" : [], # Store chain partition's key file name (with relative path)
                         "Hash" : [], # Store partitions with hash descriptors that added to vbmeta image
                         "Hashtree" : [], # Store partitions with hashtree descriptors that added to vbmeta image
                         "Algorithm" : "", # Store hash algorithm used by vbmeta image
                         "Public key (sha1)" : "" # Store public key SHA1 of vbmeta image
                         }
            info_list_length = len(image_info_list)
            encounter_string_desc = False # Has encountered string "Descriptors"? This string indicates the beginning of "other partitions' info"
            info_line = 0
            while info_line < info_list_length:
                if encounter_string_desc:
                    if "Chain" in image_info_list[info_line]:
                        self.log_if_debug("T", "Found chain partition.")
                        # In case the output sequence changes, use loop instead of hard-coded position
                        # Find partition name
                        for j in range(info_line + 1, info_line + 5): # Each chain partition has a 4-line descriptor
                            if "Name" in image_info_list[j]:
                                colon_position = image_info_list[j].find(":")
                                result_dic["Chain"].append(image_info_list[j][colon_position + 1:].strip(" "))
                                break
                        # Find rollback index location
                        for j in range(info_line + 1, info_line + 5): # Each chain partition has a 4-line descriptor
                            if "Rollback Index Location" in image_info_list[j]:
                                colon_position = image_info_list[j].find(":")
                                # always add rollback index info to the last element (which is appended by the previous "for" loop.)
                                result_dic["Chain"][-1] += ":" + image_info_list[j][colon_position + 1:].strip(" ") + ":"
                                break
                        # Find public key SHA1
                        for j in range(info_line + 1, info_line + 5):
                            self.log_if_debug("T", "Process chain partition key.")
                            if "Public key" in image_info_list[j]:
                                colon_position = image_info_list[j].find(":")
                                temp_dic = {"Public key (sha1)" : image_info_list[j][colon_position + 1:].strip(" ")}
                                result_dic["Chain partition key"].append(self.__auto_detect_key_bin(self.__auto_detect_key_file(temp_dic)["Public key file"]))
                        info_line += 5
                    elif "Hash descriptor" in image_info_list[info_line]:
                        self.log_if_debug("T", "Found hash descriptor.")
                        for j in range(info_line + 1, info_line + 7): # Each partition with a hash desc has a 6-line descriptor
                            if "Name" in image_info_list[j]:
                                colon_position = image_info_list[j].find(":")
                                result_dic["Hash"].append(image_info_list[j][colon_position + 1:].strip(" "))
                                break
                        info_line += 7
                    elif "Hashtree descriptor" in image_info_list[info_line]:
                        self.log_if_debug("T", "Found hashtree descriptor.")
                        for j in range(info_line + 1, info_line + 15): # Each partition with a hashtree desc has a 14-line descriptor
                            if "Name" in image_info_list[j]:
                                colon_position = image_info_list[j].find(":")
                                result_dic["Hashtree"].append(image_info_list[j][colon_position + 1:].strip(" "))
                                break
                        info_line += 15
                    elif "Prop" in image_info_list[info_line]:
                        self.log_if_debug("T", "Prop string detected.")
                        colon_position = image_info_list[info_line].find(":")
                        result_dic["Prop" + str(prop_count)] = image_info_list[info_line][colon_position + 1:].strip(" ")
                        prop_count += 1
                        info_line += 1
                    else:
                        info_line += 1
                else:
                    if "Descriptors:" in image_info_list[info_line]:
                        encounter_string_desc = True
                    elif "Algorithm" in image_info_list[info_line]:
                        result_dic["Algorithm"] = image_info_list[info_line][image_info_list[info_line].find(":") + 1:].strip(" ")
                    elif "Rollback" in image_info_list[info_line] and "Location" not in image_info_list[info_line]:
                        result_dic["Rollback Index"] = image_info_list[info_line][image_info_list[info_line].find(":") + 1:].strip(" ")
                    elif "Public key (sha1)" in image_info_list[info_line]:
                        result_dic["Public key (sha1)"] = image_info_list[info_line][image_info_list[info_line].find(":") + 1:].strip(" ")
                    info_line += 1
        else:
            result_dic = {}
            for info_line in image_info_list:
                colon_position = info_line.find(":")
                if colon_position != -1:
                    self.log_if_debug("T", "Find separator in line: " + info_line)
                    if "Prop" in info_line[:colon_position].strip(" "):
                        self.log_if_debug("T", "Prop string detected.")
                        result_dic[info_line[:colon_position].strip(" ") + str(prop_count)] = info_line[colon_position + 1:].strip(" ")
                        prop_count += 1
                    else:
                        result_dic[info_line[:colon_position].strip(" ")] = info_line[colon_position + 1:].strip(" ")
        self.log_if_debug("I", "Successfully parsed image info.")
        self.log_if_debug("I", "Step3, remove unnecessary key-value pairs and add some post process.")
        if is_vbmeta_image:
            # Only have to process prop
            result_dic = self.__generate_config_dict_vb(result_dic)
        else:
            # Remove unnecessary value.
            # Too many valid values, better process them in a separated method.
            result_dic = self.__generate_config_dict(result_dic)
        result_dic = self.__auto_detect_key_file(result_dic)
        return result_dic
    
    # Process props, put them into a subDictionary.
    @staticmethod
    def __generate_config_dict_vb(image_info_dic : dict) -> dict:
        result_dic = image_info_dic
        prop_list = []
        result_dic_copy = copy.deepcopy(result_dic)
        # Remove key-value pairs with empty/wrong value, process props, and detect descriptor type
        for result_dic_item in result_dic_copy:
            if "Prop" in result_dic_item:
                prop_list.append(result_dic[result_dic_item])
                result_dic.pop(result_dic_item)
        # noinspection DuplicatedCode
        prop_dic = {}
        for result_dic_item in prop_list:
            arrow_pos = result_dic_item.find("->")
            if arrow_pos != -1:
                prop_dic[result_dic_item[: arrow_pos - 1]] = result_dic_item[arrow_pos + 4: -1]
        result_dic["Props"] = prop_dic
        return result_dic

    def __generate_config_dict(self, image_info_dic : dict) -> dict:
        """
        Provide a dictionary with necessary data:
        Actual Image Size,
        Public Key,
        Algorithm,
        Rollback Index,
        Hash Algorithm,
        Partition Name,
        Salt,
        Prop (Saved in a sub-dictionary),
        Descriptor Type [Hash|Hashtree]
        """
        result_dic = image_info_dic
        # Remove useless keys
        excluded_key_list = ["Footer version", "Original image size", "VBMeta offset",
                           "VBMeta size", "Minimum libavb version", "Header Block",
                           "Authentication Block", "Auxiliary Block", "Flags",
                           "Release String", "Digest", "Flags",
                           "Descriptors", "Rollback Index Location"]
        for excluded_key in excluded_key_list:
            try:
                result_dic.pop(excluded_key)
            except Exception as e:
                self.log_if_debug("W", str(e))
        has_encounter_string = False # Has encountered string "hash(tree) descriptor"
        descriptor_type = "" # Hash or Hashtree
        prop_list = []
        result_dic_copy = copy.deepcopy(result_dic)
        # Remove key-value pairs with empty/wrong value, process props, and detect descriptor type
        for excluded_key in result_dic_copy:
            if excluded_key.lower() == "hash descriptor" or excluded_key.lower() == "hashtree descriptor":
                has_encounter_string = True
                if "hashtree" in excluded_key.lower():
                    descriptor_type = "Hashtree"
                else:
                    descriptor_type = "Hash"
                result_dic.pop(excluded_key)
            elif excluded_key == "Image Size":
                if has_encounter_string:
                    # Preserved logic, maybe Google will fix typo in newer version of avbtool.py?
                    # They use "Image size" in avbtool 1.3 to indicate actual image size.
                    result_dic.pop(excluded_key)
                else:
                    result_dic[excluded_key] = result_dic[excluded_key][:-5]
            elif excluded_key == "Image size":
                result_dic[excluded_key] = result_dic[excluded_key][:-6]
            elif "Prop" in excluded_key:
                prop_list.append(result_dic[excluded_key])
                result_dic.pop(excluded_key)
        result_dic["Descriptor Type"] = descriptor_type
        # noinspection DuplicatedCode
        prop_dic = {}
        for excluded_key in prop_list:
            arrow_pos = excluded_key.find("->")
            if arrow_pos != -1:
                prop_dic[excluded_key[: arrow_pos - 1]] = excluded_key[arrow_pos + 4: -1]
        result_dic["Props"] = prop_dic
        return result_dic
    
    def __auto_detect_key_file(self, image_info_dic : dict) -> dict:
        # Create result dictionary
        image_info_dic_copy = copy.deepcopy(image_info_dic)
        # Make sure the key cache exists
        if not os.path.exists(os.path.join(os.getcwd(),
                                           "Core",
                                           "currentKeySet",
                                           "keyCache.cache")):
            key_dir_utils = KeyDirUtils.KeyDirUtils()
            key_dir_utils.generate_key_file_cache()
        # Start detection.
        with open(os.path.join(os.getcwd(),
                                "Core",
                                "currentKeySet",
                                "keyCache.cache")) as myFile:
            file_with_sha1 = myFile.readlines()
            sha1_list = []
            '''
            The structure of sha1_list:
            [
            [filename1, sha1_1],
            [filename2, sha1_2],
            ...
            ]
            '''
            for file_line in range(len(file_with_sha1)):
                sha1_list.append(file_with_sha1[file_line].strip("\n").split(", "))
            for j in image_info_dic:
                # Look for Public key value
                if j == "Public key (sha1)":
                    self.myLogger.log("T", "Public key SHA1: " + image_info_dic[j], "autoDetectKeyFile")
                    # Start auto-matching once found public key SHA1
                    for k in range(len(sha1_list)):
                        if sha1_list[k][1] == image_info_dic[j]:
                            self.myLogger.log("T", "Key file: " + sha1_list[k][0], "autoDetectKeyFile")
                            image_info_dic_copy["Public key file"] = sha1_list[k][0]
                            break
                    else:
                        self.myLogger.log("W", "No appropriate key file found for image!", self.TAG)
                        image_info_dic_copy["Public key file"] = "NOT_FOUND"
            return image_info_dic_copy
    
    @staticmethod
    def __auto_detect_key_bin(image_info_dic) -> dict:
        return image_info_dic[:-4] + "_pub.bin"

    # Private method to read image info, will return a dictionary, will not save result to file.
    def __read_image_info_batch(self, image_list : list[str]) -> dict:
        super_result_dic = {} # Can be converted into JSON.
        for image_name in image_list:
            try:
                m_image_info_string = self.read_image_info(image_name= image_name)
            except RuntimeError:
                continue
            if "vbmeta" in image_name:
                super_result_dic[image_name] = self.__image_info_parser(m_image_info_string, True)
            else:
                super_result_dic[image_name] = self.__image_info_parser(m_image_info_string, False)
            super_result_dic[image_name]["Image File"] = image_name + ".img"
        self.myLogger.log("I", "Image info extraction ended successfully.")
        return super_result_dic
    
    # Expose to outer world, will save result to file.
    def read_image_info_batch(self, image_list : list[str]) -> None:
        self.save_result_to_file(self.__read_image_info_batch(image_list))

    def save_result_to_file(self, result_dict : dict) -> None:
        json_string = json.dumps(result_dict, indent=4, sort_keys=True)
        with open(os.path.join(os.getcwd(),
                               "Core",
                               "currentConfigs",
                               "imageInfo.json"), "w+") as myFile:
            myFile.write(json_string)
        self.myLogger.log("I", "Image info successfully written into "
                          + os.path.join(os.getcwd(),
                                        "Core",
                                        "currentConfigs",
                                        "imageInfo.json"), "saveResultToFile")

if __name__ == "__main__":
    myLogger = LogUtils.LogUtils()
    myImageInfoUtils = ImageInfoUtils()
    myConfigParser = ConfigParser.ConfigParser()
    imageList = myConfigParser.get_image_list()
    myLogger.log("I", "================================================================================", "ImageInfoUtils")
    myLogger.log("I", "Image list read from config:", "ImageInfoUtils")
    for i in imageList:
        myLogger.log("I", i + ".img", "ImageInfoUtils")
    myLogger.log("I", "================================================================================", "ImageInfoUtils")
    myImageInfoUtils.read_image_info_batch(image_list= imageList)